version: "3.0"

services:
  app_jobpipe:
    image: chourabiaziz1/job-pipe:1.0.0  # Adjusted the image name
    restart: on-failure
    depends_on:
      - mysql_db
    ports:
      - 8082:8082
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/timesheet_db?createDatabaseIfNotExist=true
    stdin_open: true
    tty: true

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=timesheet_db

volumes:
  db: 
